name: Functional tests

on:
  pull_request:
    paths:
    - 'nxdrive/**/*.py'
    - 'tests/functional/*.py'
    - 'tests/old_functional/*.py'

jobs:
  ft_linux:
    # needs: start_server
    runs-on: ubuntu-latest
    env:
      ADDITIONAL_PACKAGES: "nuxeo-drive nuxeo-platform-importer"
      NUXEO_CLID: ${{ secrets.NUXEO_CLID }}

    services:
      nuxeo:
        image: nuxeo/nuxeo:master

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7  # XXX_PYTHON

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
        restore-keys: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}

    - uses: actions/cache@v1
      with:
        path: .tox
        key: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
        restore-keys: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}

    - name: Install tox
      run: python -m pip install -r tools/deps/requirements-tox.txt

    - name: Functional tests
      run: tox -e ft

  # ft_macos:
  #   needs: start_server
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.7  # XXX_PYTHON
  #   - uses: actions/cache@v1
  #     with:
  #       path: ~/Library/Caches/pip
  #       key: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
  #       restore-keys: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
  #   - uses: actions/cache@v1
  #     with:
  #       path: .tox
  #       key: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
  #       restore-keys: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
  #   - name: Install tox
  #     run: python -m pip install -r tools/deps/requirements-tox.txt
  #   - name: Functional tests
  #     run: tox -e ft

  # ft_windows:
  #   needs: start_server
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.7  # XXX_PYTHON
  #   - uses: actions/cache@v1
  #     with:
  #       path: ~\AppData\Local\pip\Cache
  #       key: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
  #       restore-keys: ${{ runner.os }}-pip-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
    # Cannot be used for now: OSError: [WinError 193] %1 is not a valid Win32 application
    #- uses: actions/cache@v1
    #  with:
    #    path: .tox
    #    key: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
    #    restore-keys: ${{ runner.os }}-tox-${{ hashFiles('tools/deps/requirements.txt', 'tools/deps/requirements-test.txt', 'tools/deps/requirements-tox.txt') }}
    # - name: Install tox
    #   run: python -m pip install -r tools/deps/requirements-tox.txt
    # - name: Functional tests
    #   run: tox -e ft
